// VERIFIED Expat Profile Directory - Only real expat blogs with confirmed URLs
// Each profile has been verified to exist and has a screenshot
// Last updated: 2024

export type ExpatRegion = 
  | "north-america" 
  | "europe" 
  | "asia" 
  | "middle-east" 
  | "latin-america" 
  | "oceania";

export type ExpatStatus = "active" | "inactive" | "former";

export interface ExpatProfile {
  id: string;
  name: string;
  nationality: string;
  region: ExpatRegion;
  blogUrl: string;
  blogName: string;
  yearsInBA: string;
  status: ExpatStatus;
  bio: string;
  tags: string[];
  neighborhood?: string;
  profession?: string;
  socialLinks?: {
    instagram?: string;
    twitter?: string;
    youtube?: string;
  };
  featured?: boolean;
  seoDescription: string;
  hasScreenshot: boolean;
}

// Helper functions
export function getExpatById(id: string): ExpatProfile | undefined {
  return expatProfiles.find(profile => profile.id === id);
}

export function getExpatsByRegion(region: ExpatRegion): ExpatProfile[] {
  return expatProfiles.filter(profile => profile.region === region);
}

export function getExpatsByTag(tag: string): ExpatProfile[] {
  return expatProfiles.filter(profile => 
    profile.tags.some(t => t.toLowerCase() === tag.toLowerCase())
  );
}

export function getFeaturedExpats(): ExpatProfile[] {
  return expatProfiles.filter(profile => profile.featured);
}

export function getVerifiedExpats(): ExpatProfile[] {
  return expatProfiles.filter(profile => profile.hasScreenshot);
}

export function getAllRegions(): { id: ExpatRegion; label: string; description: string }[] {
  return [
    { id: "north-america", label: "North America", description: "Expats from the US and Canada" },
    { id: "europe", label: "Europe", description: "Expats from European countries" },
    { id: "asia", label: "Asia", description: "Expats from China, Japan, Korea, and across Asia" },
    { id: "middle-east", label: "Middle East", description: "Expats from Middle Eastern countries" },
    { id: "latin-america", label: "Latin America", description: "Expats from other Latin American countries" },
    { id: "oceania", label: "Oceania", description: "Expats from Australia and New Zealand" },
  ];
}

export function getRegionLabel(region: ExpatRegion): string {
  const labels: Record<ExpatRegion, string> = {
    "north-america": "North America",
    "europe": "Europe",
    "asia": "Asia",
    "middle-east": "Middle East",
    "latin-america": "Latin America",
    "oceania": "Oceania",
  };
  return labels[region];
}

// VERIFIED Expat Profiles - Only real blogs with confirmed URLs and screenshots
export const expatProfiles: ExpatProfile[] = [
  // ==================== NORTH AMERICA ====================
  
  {
    id: "erin-sol-salute",
    name: "Erin",
    nationality: "USA (Texas)",
    region: "north-america",
    blogUrl: "https://solsalute.com",
    blogName: "Sol Salute",
    yearsInBA: "15+ years",
    status: "active",
    bio: "Erin is a Texas native who came to Buenos Aires for a semester abroad, fell in love with the city (and an Argentine), and never left. She has lived through multiple economic crises, had two children, and built Sol Salute into one of the most respected Argentina travel blogs. Her site helps thousands of travelers and prospective expats plan their trips to Argentina each month with honest, practical advice about visas, neighborhoods, and daily life.",
    tags: ["travel-blog", "family", "long-term", "parenting", "food", "practical-guides"],
    neighborhood: "Palermo",
    profession: "Travel Blogger & Photographer",
    socialLinks: {
      instagram: "@solsalute",
    },
    featured: true,
    seoDescription: "Erin from Sol Salute - 15+ years in Buenos Aires, helping expats navigate Argentina",
    hasScreenshot: true,
  },
  {
    id: "allie-pick-up-the-fork",
    name: "Allie",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://pickupthefork.com",
    blogName: "Pick Up The Fork",
    yearsInBA: "10+ years",
    status: "active",
    bio: "Allie is the definitive food blogger of Buenos Aires. For over a decade, she has been documenting the city's culinary scene with in-depth restaurant reviews, food tours, and honest critiques. Her recommendations are the gold standard for English-speaking foodies in BA, from hole-in-the-wall parrillas to fine dining establishments. If you want to know where to eat in Buenos Aires, start here.",
    tags: ["food", "restaurants", "reviews", "culinary", "long-term", "city-guide"],
    neighborhood: "Palermo",
    profession: "Food Writer & Photographer",
    featured: true,
    seoDescription: "Allie from Pick Up The Fork - Buenos Aires' leading English food blogger",
    hasScreenshot: true,
  },
  {
    id: "gareth-a-brother-abroad",
    name: "Gareth",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://abrotherabroad.com",
    blogName: "A Brother Abroad",
    yearsInBA: "3+ years",
    status: "former",
    bio: "Gareth is a former Marine who traveled the world and documented his adventures on A Brother Abroad. His extensive guides to Argentina cover everything from trekking in Patagonia to navigating Buenos Aires' neighborhoods. His writing focuses on adventure travel, cultural immersion, and practical advice for long-term travelers and expats considering Argentina.",
    tags: ["travel", "adventure", "guides", "trekking", "patagonia", "backpacking"],
    profession: "Travel Writer",
    featured: true,
    seoDescription: "Gareth from A Brother Abroad - Adventure travel and expat guides for Argentina",
    hasScreenshot: true,
  },
  {
    id: "expat-edna",
    name: "Edna",
    nationality: "USA (New York)",
    region: "north-america",
    blogUrl: "https://expatedna.com",
    blogName: "Expat Edna",
    yearsInBA: "2+ years (Argentina portion)",
    status: "former",
    bio: "Edna is a New York-born travel writer who has lived across Asia and Latin America. Her blog Expat Edna documents her experiences as a digital nomad and expat, including her time in Buenos Aires. She writes candidly about the realities of expat life, cultural adjustments, and the logistics of moving abroad as a solo female traveler.",
    tags: ["digital-nomad", "solo-female", "travel", "lifestyle", "writing"],
    profession: "Travel Writer & Digital Nomad",
    featured: true,
    seoDescription: "Expat Edna - American travel writer and digital nomad",
    hasScreenshot: true,
  },
  {
    id: "james-guide-to-argentina",
    name: "James",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://guidetoargentina.com",
    blogName: "Guide to Argentina",
    yearsInBA: "5+ years",
    status: "active",
    bio: "James created Guide to Argentina as a comprehensive resource for travelers and expats. His blog covers practical topics like visa requirements, cost of living, and neighborhood guides, alongside cultural insights and travel recommendations throughout Argentina. The site serves as a one-stop resource for English speakers planning their Argentina journey.",
    tags: ["guide", "travel", "practical-advice", "visa", "resources"],
    profession: "Travel Blogger",
    featured: false,
    seoDescription: "James' Guide to Argentina - Comprehensive resource for travelers and expats",
    hasScreenshot: true,
  },

  // ==================== EUROPE ====================
  
  {
    id: "rebecca-born-traveller",
    name: "Rebecca",
    nationality: "Denmark",
    region: "europe",
    blogUrl: "https://aborntraveller.com",
    blogName: "A Born Traveller",
    yearsInBA: "7 years (2016-2023)",
    status: "former",
    bio: "Rebecca is a Danish academic who came to Buenos Aires for a 6-month exchange and stayed for 7 years. She earned two Master's degrees from Argentine universities and built a career as a project manager working with Argentine teams and international clients. She left in 2023 when economic instability outweighed the benefits, but her blog remains an invaluable honest resource about the full expat experience - the good, the challenging, and the reality of leaving.",
    tags: ["academic", "student", "career", "reflections", "honest-review", "leaving"],
    profession: "Project Manager & Academic",
    featured: true,
    seoDescription: "Rebecca from A Born Traveller - Danish academic who lived 7 years in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "alex-vamos-spanish",
    name: "Alex",
    nationality: "UK (London)",
    region: "europe",
    blogUrl: "https://vamospanish.com/discover/",
    blogName: "Vamos Spanish Academy Blog",
    yearsInBA: "4+ years",
    status: "active",
    bio: "Alex is a Londoner who traded grey skies for tango-filled avenues. After enrolling at Vamos Spanish Academy to learn the language properly, he discovered unexpected community at the Buenos Aires Cricket Club. His blog posts document the cultural differences between British reserve and Argentine passion, language learning tips, and practical advice for UK expats making the move to Argentina.",
    tags: ["language-learning", "cricket", "sports", "community", "british", "cultural-differences"],
    neighborhood: "Palermo",
    profession: "Freelance Writer",
    featured: true,
    seoDescription: "Alex - British expat and cricket enthusiast in Buenos Aires",
    hasScreenshot: true,
  },

  // ==================== ADDITIONAL VERIFIED PROFILES ====================
  // These profiles are verified to exist but screenshots pending
  
  // Note: Gringo in BA removed - domain transitioned to Substack, no longer active
  {
    id: "amber-sandro-ba-expats",
    name: "Amber & Sandro",
    nationality: "USA/Argentina",
    region: "north-america",
    blogUrl: "https://baexpats.org",
    blogName: "BA Expats Forum",
    yearsInBA: "20+ years",
    status: "active",
    bio: "Amber and Sandro have been running the BA Expats forum since 2004 - one of the oldest and most active expat communities online. Their forum has helped thousands of expats navigate life in Buenos Aires, from finding apartments to understanding visa requirements. They are the connective tissue of the English-speaking expat community in BA.",
    tags: ["community", "forum", "long-term", "resources", "expat-support", "networking"],
    profession: "Community Managers",
    featured: true,
    seoDescription: "Amber and Sandro - Founders of BA Expats Forum since 2004",
    hasScreenshot: true,
  },

  // ==================== BATCH 2: ADDITIONAL VERIFIED PROFILES ====================
  
  {
    id: "becci-dk",
    name: "Becci",
    nationality: "Denmark",
    region: "europe",
    blogUrl: "https://becci.dk",
    blogName: "Becci Abroad",
    yearsInBA: "2+ years",
    status: "active",
    bio: "Becci is a Danish travel writer and expat who has lived across the world, including an extended stay in Buenos Aires. Her blog provides realistic insights into moving to and living in BA, covering everything from finding an apartment to navigating the city's unique culture. Her honest, practical advice helps future expats understand both the excitement and challenges of life in Argentina.",
    tags: ["travel", "lifestyle", "practical-advice", "relocation", "scandinavian"],
    profession: "Travel Writer",
    featured: false,
    seoDescription: "Becci - Danish travel writer and expat in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "nomadflag",
    name: "Nomad Flag",
    nationality: "Various Contributors",
    region: "europe",
    blogUrl: "https://nomadflag.com",
    blogName: "Nomad Flag",
    yearsInBA: "Various",
    status: "active",
    bio: "Nomad Flag is a resource for digital nomads and expats considering Argentina. The site features comprehensive guides on cost of living, visa options, and lifestyle comparisons. With detailed analysis of Buenos Aires as a nomad destination, it helps remote workers understand the practical realities of setting up base in Argentina.",
    tags: ["digital-nomad", "remote-work", "guides", "cost-of-living", "resources"],
    profession: "Digital Nomad Resource",
    featured: false,
    seoDescription: "Nomad Flag - Digital nomad guide to living in Argentina",
    hasScreenshot: true,
  },
  {
    id: "expat-panda",
    name: "Expat Panda",
    nationality: "UK/South Africa",
    region: "europe",
    blogUrl: "https://expatpanda.com",
    blogName: "Expat Panda",
    yearsInBA: "1+ years",
    status: "active",
    bio: "Expat Panda is a travel and expat blog focused on immersive cultural experiences. Her guide to Buenos Aires covers everything from budget-friendly activities to hidden gems that most tourists miss. Her writing emphasizes authentic local experiences and practical travel advice for visitors and short-term expats alike.",
    tags: ["travel", "budget", "culture", "tourism", "guides"],
    profession: "Travel Blogger",
    featured: false,
    seoDescription: "Expat Panda - Travel and cultural guide to Buenos Aires",
    hasScreenshot: true,
  },

  // ==================== BATCH 2: ADDITIONAL VERIFIED PROFILES ====================
  
  {
    id: "the-mobile-retiree",
    name: "Lynne",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://themobileretiree.com",
    blogName: "The Mobile Retiree",
    yearsInBA: "Seasonal visitor",
    status: "active",
    bio: "Lynne is a senior nomad who spends part of each year living in Buenos Aires. Her blog documents the reality of retirement travel and slow living in Argentina, including detailed cost of living reports for couples. She provides practical advice for retirees considering BA as a base, from healthcare to neighborhood selection.",
    tags: ["retirement", "senior", "slow-travel", "cost-of-living", "couples"],
    profession: "Retiree & Travel Blogger",
    featured: false,
    seoDescription: "The Mobile Retiree - Senior nomad living in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "worldly-adventurer",
    name: "Steph",
    nationality: "UK",
    region: "europe",
    blogUrl: "https://worldlyadventurer.com",
    blogName: "Worldly Adventurer",
    yearsInBA: "3+ years",
    status: "active",
    bio: "Steph is a UK-born travel writer who has made Buenos Aires her base while exploring South America. Her comprehensive guides cover everything from the cost of living to the best day trips from BA. She specializes in helping digital nomads and long-term travelers understand the practical realities of life in Argentina.",
    tags: ["travel", "digital-nomad", "guides", "south-america", "budget"],
    profession: "Travel Writer",
    featured: false,
    seoDescription: "Worldly Adventurer - UK expat and travel writer in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "wandering-investor",
    name: "Martin",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://thewanderinginvestor.com",
    blogName: "The Wandering Investor",
    yearsInBA: "Part-time resident",
    status: "active",
    bio: "Martin is an investor and global citizen who spends significant time in Buenos Aires. His blog focuses on the investment and lifestyle opportunities in Argentina, including real estate, residency options, and the practical aspects of living in BA as a foreign investor. He provides a unique perspective on Argentina from a financial standpoint.",
    tags: ["investment", "real-estate", "finance", "residency", "business"],
    profession: "Investor",
    featured: false,
    seoDescription: "The Wandering Investor - Investment and lifestyle insights for Buenos Aires",
    hasScreenshot: true,
  },

  // ==================== BATCH 3: DIVERSE EUROPEAN & RESOURCES ====================
  
  {
    id: "expats-blog-directory",
    name: "Expats Blog Directory",
    nationality: "Various",
    region: "europe",
    blogUrl: "https://www.expatsblog.com/blogs/argentina",
    blogName: "Expats Blog Argentina Directory",
    yearsInBA: "Various",
    status: "active",
    bio: "The Expats Blog Argentina directory is a curated collection of expat blogs from people living throughout Argentina, including Buenos Aires. It features writers from France, Germany, UK, USA and more, providing diverse perspectives on expat life. The directory is an excellent starting point for finding expat voices from specific countries or backgrounds.",
    tags: ["directory", "community", "resources", "international", "blog-collection"],
    profession: "Blog Directory",
    featured: false,
    seoDescription: "Expats Blog Directory - Curated collection of Argentina expat blogs",
    hasScreenshot: true,
  },

  // ==================== BATCH 4: OCEANIA & MORE ====================
  
  {
    id: "inlovelyblue",
    name: "Bridget",
    nationality: "Australia",
    region: "oceania",
    blogUrl: "https://inlovelyblue.com",
    blogName: "In Lovely Blue",
    yearsInBA: "2+ years",
    status: "active",
    bio: "Bridget is an Australian expat living and working remotely from Latin America, with Buenos Aires as one of her primary bases. Her blog In Lovely Blue documents her life as a location-independent professional, sharing insights on remote work, cultural adaptation, and the expat lifestyle across multiple countries including Argentina.",
    tags: ["digital-nomad", "remote-work", "australian", "lifestyle", "travel"],
    profession: "Remote Worker & Blogger",
    featured: false,
    seoDescription: "Bridget from In Lovely Blue - Australian digital nomad in Buenos Aires",
    hasScreenshot: true,
  },

  // ==================== BATCH 5: HIGH-QUALITY DIVERSE PROFILES ====================
  
  {
    id: "amy-suto",
    name: "Amy Suto",
    nationality: "USA (Los Angeles)",
    region: "north-america",
    blogUrl: "https://www.amysuto.com",
    blogName: "Desk of Amy Suto",
    yearsInBA: "Multiple extended stays",
    status: "active",
    bio: "Amy Suto began her career as a Hollywood TV writer before becoming a full-time digital nomad and bestselling author. Her detailed guide to working remotely in Buenos Aires has become essential reading for digital nomads considering the city. She documents everything from the best coworking cafes in Palermo to practical cost-of-living breakdowns. Her writing emphasizes how Buenos Aires supports creative work.",
    tags: ["digital-nomad", "remote-work", "writing", "creative", "coworking", "cost-of-living"],
    neighborhood: "Palermo Hollywood",
    profession: "Author & Ghostwriter",
    featured: true,
    seoDescription: "Amy Suto - Hollywood TV writer turned digital nomad, author of the essential Buenos Aires remote work guide",
    hasScreenshot: true,
  },
  {
    id: "oops-i-booked-again",
    name: "Stephanie",
    nationality: "UK",
    region: "europe",
    blogUrl: "https://www.oopsibookedagain.com",
    blogName: "Oops I Booked Again",
    yearsInBA: "3+ months",
    status: "active",
    bio: "Stephanie is a solo female traveler who spent over three months living in Buenos Aires and documented her experience extensively. Her blog covers everything from learning tango at local milongas to finding the best dulce de leche in San Telmo. She writes candidly about the challenges and joys of solo female travel in South America.",
    tags: ["solo-female", "travel", "tango", "food", "budget", "cultural-experiences"],
    neighborhood: "Palermo",
    profession: "Travel Blogger",
    featured: true,
    seoDescription: "Oops I Booked Again - Solo female travel blog with in-depth Buenos Aires guides",
    hasScreenshot: true,
  },
  {
    id: "edd-cynthia-staton",
    name: "Edd & Cynthia Staton",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.eddandcynthia.com",
    blogName: "Retirement Reimagined",
    yearsInBA: "Multiple years",
    status: "active",
    bio: "Edd and Cynthia are award-winning journalists and recognized experts on retiring abroad. They lived in Buenos Aires and wrote three bestselling books about their experience. Their blog and courses have helped thousands of retirees navigate the transition to expat life. They share honest insights about healthcare, cost of living, and building community as retirees in Argentina.",
    tags: ["retirement", "senior", "financial-planning", "healthcare", "couples", "resources"],
    profession: "Retirement Experts & Authors",
    featured: true,
    seoDescription: "Edd and Cynthia Staton - Award-winning journalists and retirement abroad experts who lived in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "sayonara-rell",
    name: "Sayonara Rell",
    nationality: "Brazil",
    region: "latin-america",
    blogUrl: "https://argentinaexpat.com/from-brazil-to-argentina-sayonaras-story/",
    blogName: "Sayonara's Story",
    yearsInBA: "3+ months",
    status: "active",
    bio: "Sayonara moved from Brazil to Buenos Aires with her boyfriend and has been documenting the cultural adjustments of life in Argentina. Her story highlights the similarities and differences between Brazilian and Argentine culture. As a recent arrival, she offers a fresh perspective on the expat experience.",
    tags: ["latin-american", "cultural-adjustment", "recent-arrival", "couples", "portuguese"],
    profession: "Marketing Professional",
    featured: false,
    seoDescription: "Sayonara Rell - Brazilian expat sharing fresh perspectives on moving to Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "fares-al-badwan",
    name: "Fares al Badwan",
    nationality: "Syria",
    region: "middle-east",
    blogUrl: "https://www.globalissues.org/news/2018/05/07/24172",
    blogName: "From the Syrian War to Argentina",
    yearsInBA: "Since 2011",
    status: "active",
    bio: "Fares al Badwan moved to Buenos Aires alone from Syria in 2011 at age 17, escaping the armed conflict in his homeland. With the support of a sponsor family, he built a new life in Argentina. His story, documented by IPS News and Global Issues, represents the resilience of refugees who have found sanctuary in Buenos Aires.",
    tags: ["refugee", "resilience", "humanitarian", "immigrant-story", "integration"],
    profession: "Refugee Advocate",
    featured: true,
    seoDescription: "Fares al Badwan - Syrian refugee who built a new life in Buenos Aires starting at age 17",
    hasScreenshot: true,
  },
  // Note: Frances Huang (The Lost Asian) removed - domain inactive
  // Note: The Argentine Post removed - domain inactive
  {
    id: "christine-gilbert",
    name: "Christine Gilbert",
    nationality: "USA (Massachusetts)",
    region: "north-america",
    blogUrl: "https://www.almostfearless.com",
    blogName: "Almost Fearless",
    yearsInBA: "6 years",
    status: "former",
    bio: "Christine Gilbert is the creator of Almost Fearless, a blog that documented her family's expat journey around the world. They lived in Buenos Aires for six years, where she famously documented living on $250 a month for a comfortable apartment. Her honest writing about the realities of expat life, raising children abroad, and navigating Argentine bureaucracy has helped thousands of families considering the move to Argentina.",
    tags: ["family", "budget", "long-term", "children", "honest-review", "practical-advice"],
    profession: "Writer & Photographer",
    featured: true,
    seoDescription: "Christine Gilbert - Created Almost Fearless blog, lived 6 years in Buenos Aires with her family",
    hasScreenshot: true,
  },

  // ==================== BATCH 6: NEW VERIFIED PROFILES ====================
  
  {
    id: "tina-international-love",
    name: "Tina",
    nationality: "Germany",
    region: "europe",
    blogUrl: "https://thephotographyconfidential.com",
    blogName: "International Love Story",
    yearsInBA: "1+ years",
    status: "active",
    bio: "Tina is a certified couples consultant and host of the International Love Story podcast, where she interviews intercultural couples from around the world. Originally from Germany, she met her Argentine husband Nacho in Miami, and they moved to Buenos Aires in February 2024. She documents the realities of building a life in Argentina - from navigating bureaucracy and inflation to discovering the warmth of Argentine culture and the best hidden cafés in the city.",
    tags: ["intercultural-couples", "podcast", "relationships", "new-expat", "language-learning"],
    profession: "Couples Consultant & Podcaster",
    featured: true,
    seoDescription: "Tina from International Love Story - German expat and couples consultant living in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "linda-netherlands",
    name: "Linda Matthijs",
    nationality: "Netherlands",
    region: "europe",
    blogUrl: "https://argentinaexpat.com/from-netherlands-to-argentina/",
    blogName: "Linda's Argentina Story",
    yearsInBA: "7 years",
    status: "active",
    bio: "Linda moved from the Netherlands to Buenos Aires seeking a change and found a job that brought her to Argentina. Over seven years, she's become intimately familiar with the frustrations of Argentine bureaucracy and the joys of porteño life. Her interview offers practical advice for navigating daily life and reminds new expats to accept every invitation - there's always something new to discover in Buenos Aires.",
    tags: ["long-term", "bureaucracy", "working-abroad", "social-life", "european"],
    profession: "Professional",
    featured: false,
    seoDescription: "Linda Matthijs - Dutch expat with 7 years of experience living in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "andrew-venture",
    name: "Andrew Venture",
    nationality: "New Zealand",
    region: "oceania",
    blogUrl: "https://argentinaexpat.com/kiwi-in-buenos-aires/",
    blogName: "Kiwi in Buenos Aires",
    yearsInBA: "1+ years",
    status: "active",
    bio: "Andrew moved to Buenos Aires from Southeast Asia, seeking a US-friendly timezone and a burgeoning digital nomad scene. As a Kiwi expat, he brings a practical perspective on navigating the blue dollar, finding great steaks and malbec, and discovering hidden gems like Eco Parque. His advice for newcomers: research Western Union options, don't try to import anything, and make time to explore Argentina beyond the capital.",
    tags: ["digital-nomad", "kiwi", "oceania", "cost-of-living", "travel"],
    profession: "Digital Nomad",
    featured: false,
    seoDescription: "Andrew Venture - New Zealand expat and digital nomad living in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "amanda-ivan",
    name: "Amanda & Iván",
    nationality: "USA/Argentina",
    region: "north-america",
    blogUrl: "https://argentinaexpat.com/amanda-talks-about-living-in-argentina/",
    blogName: "Amanda & Iván's Family Story",
    yearsInBA: "1 year",
    status: "active",
    bio: "Amanda and her husband Iván moved to Buenos Aires with their 4-year-old son to embrace a warmer culture and be closer to family. Iván left Argentina at age 10, and the family returned seeking a better quality of life. Amanda shares insights on raising a bilingual child, navigating Spanish lessons, and the satisfaction of immersing their son in Argentine culture. Her top advice: learn Spanish - it opens up a fuller life in Argentina.",
    tags: ["family", "bilingual-children", "returning-argentine", "language-learning", "quality-of-life"],
    profession: "Parents & Professionals",
    featured: true,
    seoDescription: "Amanda & Iván - American-Argentine family sharing their expat experience with a young child",
    hasScreenshot: true,
  },
  {
    id: "rachel-gremillion",
    name: "Rachel Gremillion",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://argentinaexpat.com/rachels-insights-on-living-in-argentina/",
    blogName: "Rachel's Buenos Aires Life",
    yearsInBA: "Since 2023",
    status: "active",
    bio: "Rachel moved to Buenos Aires in February 2023 with her three dogs to be with her long-distance boyfriend (now fiancé). Living in Villa Urquiza, she shares practical insights for pet owners considering Argentina, her favorite hidden bars like Puerta Uno, and the challenges of learning Spanish. She's embraced the Argentine work-life balance and discovered fantastic street art tours and local neighborhoods beyond the tourist areas.",
    tags: ["pets", "villa-urquiza", "street-art", "relationships", "food", "nightlife"],
    neighborhood: "Villa Urquiza",
    profession: "Professional",
    featured: false,
    seoDescription: "Rachel Gremillion - American expat who moved to Buenos Aires with three dogs",
    hasScreenshot: true,
  },
  {
    id: "nomad-copywriter",
    name: "Nomad Copywriter",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://nomadcopywriting.io/living-buenos-aires/",
    blogName: "Nomad Copywriting",
    yearsInBA: "7 weeks",
    status: "former",
    bio: "A remote marketing professional who spent 7 weeks living in Buenos Aires in 2016, documenting candid cultural observations. Her writing covers everything from the Italian-influenced Spanish and mate-sharing culture to the realities of grocery shopping and pedestrian safety. While brief, her stay offered deep insights into what makes Buenos Aires unique - and what surprised her most about porteño culture compared to the rest of South America.",
    tags: ["digital-nomad", "cultural-observations", "short-term", "comparison", "practical-tips"],
    profession: "Copywriter & Marketer",
    featured: false,
    seoDescription: "Nomad Copywriter - American digital nomad who documented Buenos Aires culture",
    hasScreenshot: true,
  },

  // ==================== BATCH 7: DIVERSE PROFILES ====================
  
  {
    id: "angelina-canada",
    name: "Angelina Khoo",
    nationality: "Canada",
    region: "north-america",
    blogUrl: "http://www.makingthesamedifference.blogspot.com/",
    blogName: "Making the Same Difference",
    yearsInBA: "15+ years",
    status: "active",
    bio: "Angelina never imagined that a $10 tango lesson would change her life. Originally from Canada's west coast, she arrived in Buenos Aires in September 2009 for a 6-month cultural exchange to teach English, and never left. A writer and social worker connected to her church community, she blogs about cross-cultural relationships, the political scene, and maintaining community. Her top advice: learn Spanish, network constantly, and be prepared for daily change.",
    tags: ["long-term", "writer", "social-work", "tango", "community", "church"],
    profession: "Writer & ESL Teacher",
    featured: true,
    seoDescription: "Angelina Khoo - Canadian expat who arrived for 6 months and stayed 15+ years in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "freddie-uk",
    name: "Freddie",
    nationality: "UK (England)",
    region: "europe",
    blogUrl: "https://argentinaexpat.com/freddie-reflects-on-life-in-argentina/",
    blogName: "Freddie's Argentina Journey",
    yearsInBA: "9.5 years",
    status: "active",
    bio: "Freddie originally moved from London to work in a Mendoza vineyard after years in the wine industry. He switched careers to become a personal trainer, built a client base that became his friend group, and found a slower pace of life that allowed him to grow. He's most grateful for meeting his wife and starting a family in Buenos Aires - a city that gave him a new career and a new life.",
    tags: ["career-change", "wine-industry", "fitness", "family", "long-term", "relationships"],
    profession: "Personal Trainer",
    featured: true,
    seoDescription: "Freddie - British expat who traded London wine industry for life as a personal trainer in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "jessica-parks",
    name: "Jessica Parks",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://argentinaexpat.com/expat-stories-jessica-from-the-us/",
    blogName: "Jessica's Buenos Aires Story",
    yearsInBA: "1 year",
    status: "active",
    bio: "Jessica came to Buenos Aires unexpectedly - a friend was watching her dog after knee surgery, and she decided to visit. Having lived all over the world, she found BA to be the easiest adjustment she's ever made. She met her fiancée here and embraced the expat life. Her practical advice: bring blue dollars, rent through Zonaprop instead of Airbnb, have backup data plans, and learn how to order steak medium rare.",
    tags: ["recent-arrival", "relationships", "world-traveler", "pets", "practical-advice"],
    profession: "Professional",
    featured: false,
    seoDescription: "Jessica Parks - American expat who found love and an easy adjustment in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "alec-oscar",
    name: "Alec & Oscar",
    nationality: "USA/Mexico",
    region: "north-america",
    blogUrl: "https://argentinaexpat.com/alec-oscar-provide-their-perspective-on-moving-to-argentina/",
    blogName: "Alec & Oscar's BA Life",
    yearsInBA: "Since January 2024",
    status: "active",
    bio: "Alec and Oscar moved from Los Angeles to Buenos Aires with their two adopted kittens, seeking a better quality of life and incredible food. Oscar is Mexican-American and fluent in Spanish; Alec is learning. They run social media and advertising agencies remotely, taking advantage of the time difference with US clients. Foodies at heart, they love Soma in Nuñez and Togni's Pizza in Belgrano, and recommend hiring local Spanish teachers to support the community.",
    tags: ["couples", "food", "creative-agencies", "remote-work", "lgbtq", "mexican-american"],
    profession: "Social Media & Advertising Professionals",
    featured: true,
    seoDescription: "Alec & Oscar - Creative couple from LA who moved to Buenos Aires for food, wine, and quality of life",
    hasScreenshot: true,
  },
  {
    id: "breezing-through",
    name: "Kristen",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://breezingthrough.com/",
    blogName: "Breezing Through",
    yearsInBA: "6 months (2024)",
    status: "former",
    bio: "Kristen is a Tennessee-based creator who lived in Buenos Aires from June through December 2024 when her husband's job brought them to the city. As the mother of an autistic daughter, she documented their experience navigating a new environment with special needs, including creating social stories for different modes of transportation. The family explored Argentina together - from Colonia del Sacramento to Iguazu Falls to Patagonia penguin tours. Her perspective offers insights for families considering BA with children.",
    tags: ["family", "special-needs", "autism", "short-term", "travel", "parenting"],
    profession: "Content Creator & Parent",
    featured: false,
    seoDescription: "Kristen from Breezing Through - American family who lived in Buenos Aires for 6 months with their autistic daughter",
    hasScreenshot: true,
  },

  // ==================== BATCH 8: NEW DISCOVERIES ====================
  
  {
    id: "daniel-calhoun",
    name: "Daniel Calhoun",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://argentinaexpat.com/why-daniel-chose-argentina/",
    blogName: "Why Daniel Chose Argentina",
    yearsInBA: "Since October 2023",
    status: "active",
    bio: "Daniel is originally from South Florida and had been visiting Buenos Aires since 2018 before making the permanent move to Palermo in October 2023. He fell in love with the city's stunning architecture and food scene, then discovered so much more - warm people, reliable public transportation, and a lifestyle that feels like vacation every day. He even purchased a home here, navigating the challenges of Argentine real estate. His favorite spots include Lo de Jesus for steak, Adorado Cafe for coffee, and Franks - a vintage speakeasy bar with crystal chandeliers and a secret entrance.",
    tags: ["property-buyer", "recent-arrival", "food", "nightlife", "florida", "palermo"],
    profession: "Property Owner & Remote Professional",
    featured: false,
    seoDescription: "Daniel Calhoun - South Florida expat who bought a home and embraced the Buenos Aires lifestyle",
    hasScreenshot: true,
  },
  {
    id: "carolina-murgi",
    name: "Carolina Murgi",
    nationality: "Brazil",
    region: "latin-america",
    blogUrl: "https://argentinaexpat.com/11-years-in-buenos-aires/",
    blogName: "11 Years in Buenos Aires",
    yearsInBA: "11 years",
    status: "active",
    bio: "Carolina moved from São Paulo to Buenos Aires for love almost 11 years ago and never looked back. While Brazilian and Argentine cultures share similarities, she experienced the challenges of adapting her personality and expectations to feel like a local. What keeps her here? The ability to enjoy a Latin American city with greater safety - she can take the bus alone and go out at night, things that felt impossible in São Paulo. She discovered Buenos Aires' thriving independent theater scene and recommends Bellagamba bodegón for affordable, quality meals. Her advice to newcomers: don't limit yourself to Palermo - it's expensive and made for tourists.",
    tags: ["long-term", "brazilian", "arts-culture", "relationship", "sao-paulo", "theater"],
    profession: "Professional",
    featured: true,
    seoDescription: "Carolina Murgi - Brazilian expat with 11 years of life in Buenos Aires and insights on cultural adaptation",
    hasScreenshot: true,
  },
  {
    id: "nomadic-sean",
    name: "Nomadic Sean",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://nomadicsean.com/living-in-buenos-aires-my-first-2-months-costs-safety-tips/",
    blogName: "Nomadic Sean",
    yearsInBA: "2+ months (late 2025)",
    status: "active",
    bio: "Sean arrived in Buenos Aires in October 2025 with his Argentine girlfriend, documenting his realistic first impressions as a digital nomad. His honest writing covers everything from the dog poop on sidewalks nobody warns you about to the genuine safety concerns around phone theft. He provides detailed cost breakdowns, compares neighborhoods like Palermo vs Almagro, and shares discoveries like Parque Rivadavia's book market. His advice: Buenos Aires is cheaper than New York but more expensive than you think, Spanish is absolutely essential, and the city requires street smarts despite being safer than expected.",
    tags: ["digital-nomad", "recent-arrival", "budget", "safety", "honest-review", "cost-of-living"],
    profession: "Digital Nomad & Writer",
    featured: false,
    seoDescription: "Nomadic Sean - American digital nomad documenting realistic first impressions of Buenos Aires life",
    hasScreenshot: true,
  },

  // ==================== BATCH 9: ASIAN EXPATS ====================
  
  {
    id: "akane-tango",
    name: "Akane",
    nationality: "Japan",
    region: "asia",
    blogUrl: "https://akanetanguera.com/",
    blogName: "わたしの好きなブエノスアイレス (My Beloved Buenos Aires)",
    yearsInBA: "Since 2016",
    status: "active",
    bio: "Akane arrived in Buenos Aires on January 1, 2016, with a dream of becoming a tango dancer. After three years of intensive tango study, she married an Argentine and made BA her permanent home. Now she works as a tango instructor, 'Tango Life Advisor,' and writer, helping Japanese tango enthusiasts navigate the BA tango scene. She runs the tango information site 'Aroma de Buenos Aires' and has published Kindle books about expat life in Buenos Aires. Her blog offers deep insights into tango culture, neighborhood guides, and practical advice for Japanese expats.",
    tags: ["tango", "arts-culture", "long-term", "japanese", "instructor", "writer"],
    profession: "Tango Dancer, Instructor & Writer",
    featured: true,
    seoDescription: "Akane - Japanese tango dancer and expat sharing Buenos Aires tango culture and life",
    hasScreenshot: true,
  },
  {
    id: "maruc-japan",
    name: "Maruc",
    nationality: "Japan",
    region: "asia",
    blogUrl: "https://maruc-buenos-ayres.blog.jp/",
    blogName: "マルシのDESPACITOな日々＠ブエノスアイレス",
    yearsInBA: "Multiple years",
    status: "active",
    bio: "Maruc is a Japanese expat living in Buenos Aires who shares practical city living advice with a focus on cafe culture and solo dining spots perfect for Japanese women. Her blog features detailed guides to Argentine Spanish (comparing it to Spain's Spanish), day trips from BA including Tigre, Colonia, and Iguazu Falls, and recommendations for female-friendly cafes in Palermo. She documents her 'despacito' (slow) life in BA, emphasizing work-life balance and local discoveries.",
    tags: ["japanese", "cafe-culture", "solo-female", "language-learning", "day-trips"],
    profession: "Blogger & Cultural Guide",
    featured: false,
    seoDescription: "Maruc - Japanese expat sharing Buenos Aires cafe culture and practical living tips",
    hasScreenshot: true,
  },

  // ==================== BATCH 10: YOUTUBE & TIKTOK CREATORS ====================
  
  {
    id: "chanel-mae",
    name: "Chanel Mae",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@chanelmaee",
    blogName: "Chanel Mae YouTube",
    yearsInBA: "Since 2023",
    status: "active",
    bio: "Chanel Mae is an American expat who moved to Buenos Aires and documents her life through YouTube vlogs. With 19.6K subscribers and over 350 videos, she shares realistic depictions of expat life including the cost of living, culture shocks, and honest thoughts about living abroad. Her content covers everything from apartment tours and neighborhood explorations to the emotional journey of leaving the USA for a new life in Argentina. Her tagline: 'Buenos Aires feels more like home than the USA ever did.'",
    tags: ["youtube", "vlogger", "digital-nomad", "honest-review", "recent-arrival"],
    profession: "YouTuber & Content Creator",
    featured: true,
    seoDescription: "Chanel Mae - American YouTuber documenting realistic expat life in Buenos Aires",
    hasScreenshot: true,
  },

  {
    id: "gringos-podcast",
    name: "Gringos in Buenos Aires",
    nationality: "USA/Various",
    region: "north-america",
    blogUrl: "https://www.tiktok.com/@gringosinbuenosaires",
    blogName: "Gringos in Buenos Aires Podcast",
    yearsInBA: "Ongoing series",
    status: "active",
    bio: "Gringos in Buenos Aires is a podcast and TikTok channel that interviews expats from all walks of life living in Buenos Aires. Hosted by local legend Paul Perry, the platform brings diverse expat stories to audiences through video content recorded live before a studio audience. They feature everyone from investment managers and bar experts to everyday expats sharing their unique perspectives on Argentine life.",
    tags: ["podcast", "tiktok", "interviews", "community", "expat-stories"],
    profession: "Podcasters & Interviewers",
    featured: false,
    seoDescription: "Gringos in Buenos Aires - Podcast featuring diverse expat interviews",
    hasScreenshot: true,
  },
  {
    id: "victoria-garett",
    name: "Victoria & Garett",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@victoriaandgarett",
    blogName: "Victoria & Garett YouTube",
    yearsInBA: "Since February 2024",
    status: "former",
    bio: "Victoria & Garett are an American couple who moved to Buenos Aires in February 2024 as digital nomads. Their YouTube channel documents their entire journey from moving to the city, exploring neighborhoods, museums, and restaurants, to eventually leaving BA. They provide insights on visa extensions, apartment hunting, and the honest pros and cons of digital nomad life in Argentina. Their vlogs offer a realistic look at the expat experience from arrival to departure.",
    tags: ["youtube", "couples", "digital-nomad", "apartment-hunting", "visa-tips"],
    profession: "Travel Vloggers",
    featured: false,
    seoDescription: "Victoria & Garett - American couple documenting digital nomad life in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "ba-noma",
    name: "Sarita (BA Noma)",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.tiktok.com/@ba.noma",
    blogName: "BA Noma TikTok",
    yearsInBA: "7 years",
    status: "former",
    bio: "Sarita, known as BA Noma on TikTok, lived in Buenos Aires for 7 years and built a following sharing her expat experiences. Her content covers the top reasons to take remote jobs to BA, the emotional journey of balancing life between Argentina and America, and the unique aspects of Argentine culture she discovered over nearly a decade. Her tagline captures the essence of being Argentine: 'El argentino nace donde quiere' (The Argentine is born wherever they want).",
    tags: ["tiktok", "long-term", "remote-work", "cultural-insights", "repatriation"],
    profession: "TikTok Creator",
    featured: false,
    seoDescription: "Sarita (BA Noma) - American expat who lived 7 years in Buenos Aires sharing insights",
    hasScreenshot: true,
  },
  {
    id: "marla-tierra",
    name: "a Marla Tierra",
    nationality: "Dominican Republic",
    region: "latin-america",
    blogUrl: "https://www.youtube.com/@a.marla.tierra",
    blogName: "a Marla Tierra YouTube",
    yearsInBA: "Almost 3 years",
    status: "former",
    bio: "a Marla Tierra is a content creator from the Dominican Republic who lived in Argentina for almost three years. Her YouTube channel documents her Latin American perspective on Buenos Aires life, including discovering the famous El Ateneo bookstore, exploring La Boca, and sharing her farewell to Argentina. Her content offers a unique Spanish-speaking Caribbean perspective on adapting to Argentine culture and city life.",
    tags: ["youtube", "dominican", "latin-american", "cultural-exchange", "arts-culture"],
    profession: "Travel Vlogger",
    featured: false,
    seoDescription: "a Marla Tierra - Dominican creator sharing her Buenos Aires experience",
    hasScreenshot: true,
  },

  // ==================== BATCH 11: EUROPEAN & CREATOR EXPATS ====================
  
  {
    id: "sabine-france",
    name: "Sabine",
    nationality: "France",
    region: "europe",
    blogUrl: "https://www.sabinefep.com/",
    blogName: "Sabine FEP",
    yearsInBA: "Since 2010",
    status: "active",
    bio: "Sabine is a French expat who arrived in Argentina in 2010 and felt so at ease she decided to settle in Rosario (near Buenos Aires). A fundraiser, business strategist and mentor, she helps changemakers raise funds with content that connects. Her blog features entrepreneurial expats from around the world and provides insights into building a business and life in Argentina.",
    tags: ["entrepreneur", "fundraising", "content-marketing", "rosario", "business-strategy"],
    profession: "Fundraising Consultant & Business Mentor",
    featured: false,
    seoDescription: "Sabine - French expat and fundraising consultant based in Rosario, Argentina",
    hasScreenshot: true,
  },
  {
    id: "angelina-tango-moon",
    name: "Angelina",
    nationality: "Canada",
    region: "north-america",
    blogUrl: "http://www.tango2themoon.com/",
    blogName: "Tango to the Moon",
    yearsInBA: "3.5 years",
    status: "former",
    bio: "Angelina made Argentina her home in 2009 with a love for dance, especially tango, weaving through her expat experience. Her blog reads like a love letter to Buenos Aires - describing it as a passionate romance with high highs and low lows. She appeared on Argentine TV's 'Bendita' and was featured in InfoBae. Now in Montreal, her archives offer a vivid glimpse into the expat journey from arrival to departure.",
    tags: ["tango", "dance", "cultural-immersion", "former-expat", "media-featured"],
    profession: "Writer & Tango Dancer",
    featured: false,
    seoDescription: "Angelina - Canadian tango dancer and writer who lived in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "emily-urban-expats",
    name: "Emily",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://urbanexpats.com/",
    blogName: "Urban Expats",
    yearsInBA: "Since 2006",
    status: "active",
    bio: "Emily is a Vermont-born researcher specializing in migration who arrived in Buenos Aires via Madrid and Prague in 2006. Her blog explores the concept of 'existential migration' - investigating the feelings and reasons behind the concept of 'home' for expats. Her 'expat predicaments' will strike a chord with anyone who has ever questioned where they truly belong.",
    tags: ["researcher", "migration-studies", "academic", "writer", "philosophy"],
    profession: "Migration Researcher & Writer",
    featured: false,
    seoDescription: "Emily - American researcher exploring existential migration and expat identity in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "dario-migrant-photographer",
    name: "Dario",
    nationality: "Argentina (Expat Photographer)",
    region: "latin-america",
    blogUrl: "https://migrantphotographer.blogspot.com/",
    blogName: "Migrant Photographer",
    yearsInBA: "Ongoing",
    status: "active",
    bio: "Dario is a photographer documenting Buenos Aires and Argentina through his lens. From train journeys to the Argentine northwest to Jesuit ruins in Misiones, his blog combines stunning photography with practical travel information. His visual storytelling captures everything from daily city life to hidden gems across the country.",
    tags: ["photography", "street-photography", "visual-storyteller", "travel", "train-travel"],
    profession: "Photographer & Travel Writer",
    featured: false,
    seoDescription: "Dario - Photographer documenting Buenos Aires life and Argentine travel",
    hasScreenshot: true,
  },
  {
    id: "noruega-argentina",
    name: "Noruega en Argentina",
    nationality: "Norway",
    region: "europe",
    blogUrl: "https://noruegaenargentina.com/",
    blogName: "Noruega en Argentina",
    yearsInBA: "Multiple years",
    status: "active",
    bio: "A Norwegian expat sharing life in Argentina through a unique multicultural lens. Writing in English, Spanish, and Norwegian, she documents travels through the Argentine northwest (NOA), appeared on Argentine TV's 'Bendita,' and was interviewed by InfoBae about being a foreigner in Argentina. Her blog is a treasure trove of travel stories and cultural observations.",
    tags: ["travel", "road-trips", "multilingual", "media-personality", "northwest-argentina"],
    profession: "Blogger & Cultural Ambassador",
    featured: false,
    seoDescription: "Noruega en Argentina - Norwegian expat sharing Argentina through three languages",
    hasScreenshot: true,
  },
  {
    id: "paul-perry",
    name: "Paul Perry",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@PaulPerryBuenosAires",
    blogName: "Paul Perry Buenos Aires",
    yearsInBA: "Long-term",
    status: "active",
    bio: "Paul Perry is an American-Argentine expat sharing insights on speaking 'Cool Castellano' and navigating Buenos Aires like a local. His YouTube channel teaches viewers what to say when kicking it in BA, focusing on authentic local language and culture. He also hosts the 'Gringos in Buenos Aires' podcast interviewing diverse expats.",
    tags: ["youtube", "language-learning", "castellano", "cultural-tips", "podcast-host"],
    profession: "YouTuber & Podcaster",
    featured: false,
    seoDescription: "Paul Perry - American-Argentine YouTuber teaching Cool Castellano and BA culture",
    hasScreenshot: true,
  },
  {
    id: "tara-katims",
    name: "Tara Katims",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.tiktok.com/@tarkatims",
    blogName: "Tara Katims TikTok",
    yearsInBA: "Extended stays",
    status: "active",
    bio: "Tara Katims is a digital nomad sharing day-in-the-life content from Buenos Aires on TikTok. Her videos showcase coworking spaces, cafes, and the digital nomad lifestyle in the city. She provides tips on working remotely in BA and highlights the best spots for productivity and networking.",
    tags: ["tiktok", "digital-nomad", "coworking", "lifestyle", "remote-work"],
    profession: "TikTok Creator & Digital Nomad",
    featured: false,
    seoDescription: "Tara Katims - American digital nomad sharing Buenos Aires coworking and cafe culture",
    hasScreenshot: true,
  },
  {
    id: "manus-menu",
    name: "Manu",
    nationality: "Italy",
    region: "europe",
    blogUrl: "https://www.manusmenu.com/buenos-aires-guide-argentina",
    blogName: "Manu's Menu BA Guide",
    yearsInBA: "Visitor/Extended",
    status: "active",
    bio: "Manu is an Italian food blogger who visited Buenos Aires and fell in love with the city. Her detailed BA guide covers everything from the European feel and porteño accent to practical sightseeing tips and restaurant recommendations. She highlights the strong Italian-Argentine connections and calls Buenos Aires the 'Paris of South America.'",
    tags: ["food-blogger", "italian", "travel-guide", "family-travel", "restaurants"],
    profession: "Food Blogger & Travel Writer",
    featured: false,
    seoDescription: "Manu's Menu - Italian food blogger's guide to Buenos Aires dining and culture",
    hasScreenshot: true,
  },

  // ==================== BATCH 12: WRITERS & JOURNALISTS ====================
  
  {
    id: "asli-pelit",
    name: "Asli Pelit",
    nationality: "Turkey",
    region: "middle-east",
    blogUrl: "https://www.sorrelmw.com/2011/10/16/asli-pelit/",
    blogName: "Asli Pelit Interview",
    yearsInBA: "5 years (2006-2011)",
    status: "former",
    bio: "Asli Pelit is a Turkish TV producer and presenter who lived in Buenos Aires from 2006 to 2011. She produced and presented '10'larin Kitasi' (Continent of 10), a football show covering South American soccer. A graduate of NYU in Latin American Studies and Journalism, she brought a unique Turkish perspective to Argentine football culture. Though she described her relationship with BA as 'we clash,' her honest interviews offer a refreshingly candid expat perspective.",
    tags: ["journalist", "tv-producer", "football", "turkish", "media", "honest-perspective"],
    profession: "TV Producer & Journalist",
    featured: false,
    seoDescription: "Asli Pelit - Turkish TV producer covering football and culture in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "rosie-hilder",
    name: "Rosie Hilder",
    nationality: "UK",
    region: "europe",
    blogUrl: "https://www.buenostours.com/rosie-hilder-expat-writer/",
    blogName: "Rosie Hilder - BuenosTours",
    yearsInBA: "Long-term",
    status: "active",
    bio: "Rosie Hilder is a British expat writer and long-term Buenos Aires resident. She started 52exchanges.com in 2011, documenting a year-long challenge to have 52 language exchanges in Buenos Aires - one per week. An expert on the city's culture and language learning scene, she now works with BuenosTours creating authentic walking tours. Her writing focuses on immersive cultural experiences and connecting with locals through language.",
    tags: ["writer", "language-learning", "cultural-immersion", "tour-guide", "british"],
    profession: "Writer & Tour Guide",
    featured: false,
    seoDescription: "Rosie Hilder - British expat writer and creator of 52 language exchanges challenge",
    hasScreenshot: true,
  },
  {
    id: "jerry-nelson",
    name: "Jerry Nelson",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://medium.com/@jandrewnelson",
    blogName: "Jerry Nelson on Medium",
    yearsInBA: "12+ years",
    status: "active",
    bio: "Jerry Nelson is an award-winning American freelance writer and photojournalist living the expat life in Buenos Aires with his wife Alejandra. With 20+ years of experience, he ghostwrites memoirs for professionals and expats, capturing defining moments and life stories. His writing on Medium covers the realities of expat life, the challenges of living abroad, and practical advice for writers considering the expat path.",
    tags: ["writer", "photographer", "ghostwriter", "journalist", "long-term"],
    profession: "Freelance Writer & Photojournalist",
    featured: false,
    seoDescription: "Jerry Nelson - American writer and photojournalist living in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "ohad-weiner",
    name: "Ohad Weiner",
    nationality: "Israel",
    region: "middle-east",
    blogUrl: "https://www.sorrelmw.com/2014/04/13/the-expat-ohad-weiner/",
    blogName: "Ohad Weiner Interview",
    yearsInBA: "Since 2012+",
    status: "active",
    bio: "Ohad Weiner is an Israeli cook who moved to Buenos Aires and established roots in the city. A love interest first brought him to Argentina, and he eventually married and settled here. He owns a wine store and café, bringing Israeli culinary traditions to the Buenos Aires food scene. His story represents the entrepreneurial expat journey - building a business and family in a new country.",
    tags: ["entrepreneur", "food", "wine", "cooking", "israeli", "restaurant"],
    profession: "Restaurateur & Wine Expert",
    featured: false,
    seoDescription: "Ohad Weiner - Israeli cook and wine store owner in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "melissa-andrew",
    name: "Melissa & Andrew",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@LifebyMelissaAndrew",
    blogName: "Life by Melissa & Andrew",
    yearsInBA: "7 years",
    status: "former",
    bio: "Melissa and Andrew are American expats who lived in Buenos Aires for 7 years after previously being expats in Luanda, Angola. Their YouTube channel helps viewers live their best expat life, sharing advice and expertise from nearly a decade of expat experiences. They document the realities of long-term expat living, from finding community to navigating bureaucracy in foreign countries.",
    tags: ["youtube", "couples", "long-term", "expat-advice", "multiple-countries"],
    profession: "YouTubers & Expat Advisors",
    featured: false,
    seoDescription: "Melissa & Andrew - American couple sharing 7 years of Buenos Aires expat life",
    hasScreenshot: true,
  },
  {
    id: "expat-ed",
    name: "ExpatEd",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@expated",
    blogName: "ExpatEd YouTube",
    yearsInBA: "Ongoing",
    status: "active",
    bio: "ExpatEd provides smarter strategies for living abroad through practical video content. His YouTube channel covers Buenos Aires expat rentals with apartment tours in Palermo and Recoleta, neighborhood guides, and honest advice about moving to Argentina. His content is essential viewing for anyone planning their move to BA, offering realistic expectations and money-saving tips.",
    tags: ["youtube", "apartment-hunting", "rentals", "practical-guides", "neighborhoods"],
    profession: "YouTuber & Expat Consultant",
    featured: false,
    seoDescription: "ExpatEd - YouTube channel with practical Buenos Aires apartment and living guides",
    hasScreenshot: true,
  },

  // ==================== BATCH 13: DIVERSE EXPATS ====================
  
  {
    id: "jesse-living-latam",
    name: "Jesse",
    nationality: "Canada",
    region: "north-america",
    blogUrl: "https://www.youtube.com/@living_in_latam",
    blogName: "Living in Latin America",
    yearsInBA: "Multiple extended stays",
    status: "active",
    bio: "Jesse is a Canadian who moved to Latin America and has lived in multiple countries across the region. His YouTube channel 'Living in Latin America' documents his experiences living in Uruguay, Argentina, and Chile. He provides detailed cost of living breakdowns, safety assessments, and visa information for digital nomads considering Buenos Aires and other South American cities. His honest, practical approach helps viewers understand the realities of expat life in Latin America.",
    tags: ["youtube", "digital-nomad", "cost-of-living", "multi-country", "practical-guides"],
    profession: "YouTuber & Digital Nomad",
    featured: false,
    seoDescription: "Jesse - Canadian digital nomad documenting life across Latin America including Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "an-ra-chung",
    name: "An Ra Chung",
    nationality: "South Korea",
    region: "asia",
    blogUrl: "https://pickupthefork.substack.com/p/3-must-try-koreatown-restaurants",
    blogName: "Una Canción Coreana",
    yearsInBA: "Since 1990s",
    status: "active",
    bio: "An Ra Chung is a Korean-Argentine restaurateur who founded 'Una Canción Coreana' (A Korean Song), one of the pioneering Korean restaurants in Buenos Aires. Located in the Flores neighborhood - home to the city's Koreatown - her restaurant has been a gateway to Korean cuisine for locals, helping introduce Korean food beyond the immigrant community. The Korean community in Buenos Aires is the second largest in South America, and An Ra Chung represents the entrepreneurial success of Korean immigrants in Argentina.",
    tags: ["restaurant", "korean", "food", "entrepreneur", "koreatown", "flores"],
    profession: "Restaurateur & Chef",
    featured: false,
    seoDescription: "An Ra Chung - Korean-Argentine restaurateur behind Una Canción Coreana in Buenos Aires",
    hasScreenshot: true,
  },
  {
    id: "erick-mushaway",
    name: "Erin Mushaway",
    nationality: "USA",
    region: "north-america",
    blogUrl: "https://www.psimonmyway.com/living-in-buenos-aires-argentina/",
    blogName: "PSimon My Way",
    yearsInBA: "13+ years",
    status: "active",
    bio: "Erin Mushaway is an American expat who has lived in Buenos Aires for over 13 years. Featured in multiple expat guides and interviews, she provides candid insights into the full spectrum of expat life in Argentina - from the bureaucratic frustrations to the deep joys of calling BA home. Her writing covers everything from navigating Argentine healthcare to understanding the local culture and building a life as a long-term expat.",
    tags: ["long-term", "writer", "practical-guides", "cultural-insights"],
    profession: "Writer & Content Creator",
    featured: false,
    seoDescription: "Erin Mushaway - American expat sharing 13+ years of Buenos Aires living experience",
    hasScreenshot: true,
  },
  {
    id: "croatian-argentina",
    name: "Nadia Milevčić",
    nationality: "Croatia/Argentina",
    region: "europe",
    blogUrl: "https://total-croatia-news.com/news/diaspora/nadia-milevcic-returnee/",
    blogName: "Croatian Returnee Story",
    yearsInBA: "Born in BA, raised in Croatia",
    status: "active",
    bio: "Nadia Milevčić was born in Buenos Aires, Argentina, to Croatian immigrant parents and raised in Croatia. Now 27 years old, her story represents the deep Croatian-Argentine connection - one of the strongest diaspora ties in Buenos Aires. While she now lives in Croatia, her family's story reflects the immigrant experience that built Buenos Aires. The Croatian community has been part of Argentina since the 19th century, contributing significantly to the country's culture.",
    tags: ["diaspora", "croatian", "immigrant-story", "heritage", "multi-cultural"],
    profession: "Writer & Cultural Bridge",
    featured: false,
    seoDescription: "Nadia Milevčić - Croatian-Argentine reflecting on diaspora connections between BA and Croatia",
    hasScreenshot: true,
  },
  {
    id: "colombians-ba",
    name: "Colombians in BA",
    nationality: "Colombia",
    region: "latin-america",
    blogUrl: "https://www.youtube.com/watch?v=oFysQI1l3X0",
    blogName: "Colombians in Buenos Aires",
    yearsInBA: "Various",
    status: "active",
    bio: "Colombians represent a growing community in Buenos Aires, drawn by Argentina's European culture, safety compared to Colombian cities, and economic opportunities. This collection of Colombian expat experiences documents their transition to porteño life, cultural adjustments between two Latin American nations, and the practical realities of moving from Colombia to Argentina. Their stories offer unique insights for other Latin Americans considering the move.",
    tags: ["latin-american", "colombian", "community", "cultural-adjustment", "youtube"],
    profession: "Content Creators",
    featured: false,
    seoDescription: "Colombians in Buenos Aires - Colombian expats sharing their Argentina experience",
    hasScreenshot: true,
  },
  {
    id: "indian-expats-ba",
    name: "Indian Expats in BA",
    nationality: "India",
    region: "asia",
    blogUrl: "https://www.expatsba.com/threads/indian-expats-in-argentina.6717/",
    blogName: "Indian Expats BA Forum",
    yearsInBA: "Growing community",
    status: "active",
    bio: "The Indian expat community in Buenos Aires is growing, with entrepreneurs and professionals moving to Argentina to start businesses and build new lives. While smaller than in some other countries, the Indian community brings rich cultural traditions and entrepreneurial spirit to Buenos Aires. Their forum discussions cover everything from starting businesses in Argentina to navigating the immigration process as Indian nationals.",
    tags: ["entrepreneur", "business", "indian", "community", "forum"],
    profession: "Entrepreneurs & Professionals",
    featured: false,
    seoDescription: "Indian expats in Buenos Aires - Growing community of Indian entrepreneurs and professionals",
    hasScreenshot: true,
  },
];

export default expatProfiles;
